#!/usr/bin/env python

import time, os
import booklist

data = "bookdata/books.xml"
mtime = os.stat(data).st_mtime

intro = u"<p> \
    Here I have gathered some of the books I have read \
    during the 21st century. You might catch some \
    literature tips, especially, if you know me \
    and/or share my taste of thought. The topics \
    vary from historical essay to satire to \
    formal philosophical pondering. Most of them \
    are (as of Jun., 2007) actually in Finnish. \
    </p><p> \
    The ratio from one to five expresses my personal \
    feeling about the book. A book rated below three \
    did not satisfy me. A book with ratio of three was a good \
    one and I'd recommend it to others as well. Ratios of \
    four and five map to \"awesome\" and \"all time favourite\", \
    respectively. Some highly valued classics may end up \
    with a low ratio in my list. That's probably not because \
    they are trash in themselves but rather I did not \
    understand their deep message. Or maybe they are trash. \
    Who knows and who is to decide in the end? \
    </p><p> \
    The year associated with the book indicates the year \
    I read it. \
    </p><p> \
    The list is generated by my second-generation booklist generator, \
    that is written in Python. \
    The <a href='http://cs.helsinki.fi/u/avuori/books/books.xml'>old one</a> \
    was generated with an XSL \
    style sheet. The educational motive of the new version was to \
    experimentate with Python's xml.dom.minidom library as well as \
    with inline base64-encoded images (look at how the stars are being generated \
    by javascript). \
    </p><p>Muokattu viimeksi %s.</p><hr />" \
	% time.strftime("%d.%m.%Y klo %H:%M", time.localtime(mtime))

t = time.time()
booklist.OutputHandler().run(data,
                             "Some of the books I have read during the 21st century",
                             intro,
                             "./books.css")
print u"\n<!-- Generation took %d milliseconds. -->" % ((time.time()-t) * 10**3)
